Resources:
  WorkordersClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.workordersClientsTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: clientId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: clientId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}