Resources:
  WorkordersItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: itemtId
          AttributeType: S
        - AttributeName: workorderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: clientId
          AttributeType: S
      KeySchema:
        - AttributeName: workorderId
          KeyType: HASH
        - AttributeName: itemId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: workordersItemsUserGSI
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: itemId
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughputs:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: workordersItemsClientGSI
          KeySchema:
            - AttributeName: clientId
              KeyType: HASH
            - AttributeName: itemId
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughputs:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}