Resources:
  WorkordersItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.workordersItemsTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: workordersItemId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: workordersItemId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}